### ISSUE TITLE
Missing API reference for the Microsoft.CodeAnalysis namespace

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn-api-docs#18]
I was looking for API reference of the `Microsoft.CodeAnalysis.ISymbol` interface and couldn't find it. Turns out, almost the whole [`Microsoft.CodeAnalysis` namespace](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis) is missing. The only type there is from the `Microsoft.CodeAnalysis.CSharp` assembly, while most of the types, including `ISymbol`, are in the `Microsoft.CodeAnalysis` assembly.

**Comment by BillWagner** [comment]
Paging @dend I think this is related to the build warnings I'm getting on the first conceptual PR on docs. 

Can we touch base on the right fix here?

**Comment by svick** [comment]
This doesn't seem to be fixed, the example of `Microsoft.CodeAnalysis.ISymbol` still isn't part of the API reference.

Since https://github.com/dotnet/docs/pull/3523 is already included in `live`, shouldn't it be?

**Comment by BillWagner** [comment]
@dend and I are looking into this.  Reopening.

**Comment by dend** [comment]
I am currently re-running the CI job on the assemblies, to make sure that I did not miss any extracted information. Will update the content ASAP.

**Comment by dend** [comment]
@BillWagner @svick what package is `Microsoft.CodeAnalysis.ISymbol` sourced from?

**Comment by BillWagner** [comment]
@dend That should be in [Microsoft.CodeAnalysis.Common](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Common/)

**Comment by svick** [comment]
@BillWagner [Exactly.](http://dotnetapis.com/pkg/Microsoft.CodeAnalysis.Common/2.4.0/netstandard1.3/doc/Microsoft.CodeAnalysis.ISymbol)

**Comment by dend** [comment]
@BillWagner would it make sense to just wrap the package APIs under a single Roslyn moniker, instead of a per-package view?

**Comment by BillWagner** [comment]
Yes, I think so. Most users will download the single metapackage, [Microsoft.CodeAnalysis](https://www.nuget.org/packages/Microsoft.CodeAnalysis/) 

I think a single moniker that covers all the packages that are part of this meta-package would be the right behavior.

**Comment by dend** [comment]
On it. Currently re-running the CI.

**Comment by dend** [comment]
PR building here for the missing APIs, and re-organization under a single moniker:

https://github.com/dotnet/roslyn-api-docs/pull/20

**Comment by dend** [comment]
PR passed validation, so I am currently PR-ing changes into `live`: https://github.com/dotnet/roslyn-api-docs/pull/21

Once the build completes, and we merge the changes, we can consolidate the moniker in the API Browser and update the published content.

**Comment by dend** [comment]
PR merged into live. We are waiting for updates to the API Browser.

**Comment by BillWagner** [comment]
@svick I think we have everything loaded.  [See here](https://docs.microsoft.com/en-us/dotnet/api/?term=Microsoft.CodeAnalysis)  Can give it a spot check and close it if you think we've caught everything?

**Comment by svick** [comment]
@BillWagner 

It's better. Here are the issues I noticed:

1. [The search can't find `ISymbol`](https://docs.microsoft.com/en-us/dotnet/api/?term=microsoft.codeanalysis.isymbol), (even though [its page now does exist](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.isymbol?view=roslyn-dotnet)).
2. I can't find workspace-related types. For example, the `Microsoft.CodeAnalysis.Workspace` type ([from the Microsoft.CodeAnalysis.Workspaces.Common package](http://dotnetapis.com/pkg/Microsoft.CodeAnalysis.Workspaces.Common/2.4.0/netstandard1.3/doc/Microsoft.CodeAnalysis.Workspace)) doesn't seem to be included. Should it be?
3. Some of the summaries are badly formatted, but I assume that's part of https://github.com/dotnet/roslyn-api-docs/issues/1.

**Comment by dend** [comment]
It's not fully loaded yet - these are not part of the API Browser experience just yet. We're working on it.

cc: @svick @BillWagner

**Comment by dend** [comment]
This should be taken care of now.

https://docs.microsoft.com/en-us/dotnet/api/?view=roslyn-dotnet
