### ISSUE TITLE
API search results in 404

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn-api-docs#19]
When I search for a Roslyn-related API in the API search page, the results lead to the wrong URLs, which are 404.

For example, [searching for "Microsoft.CodeAnalysis.CSharp"](https://docs.microsoft.com/en-us/dotnet/api/?term=Microsoft.CodeAnalysis.CSharp) leads to https://docs.microsoft.com/en-us/roslyn-dotnet-api/api/microsoft.codeanalysis.csharp, which is 404. The correct URL seems to be https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.

**Comment by dend** [comment]
This is fixed now. Thanks for the report!
