### ISSUE TITLE
Breadcrumbs not showing up

### ISSUE THREAD

**Issue by svick** [dotnet/roslyn-api-docs#26]
Pages in Roslyn API reference don't seem to have breadcrumbs. Compare e.g. [`MethodDeclarationSyntax.Modifiers`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.syntax.methoddeclarationsyntax.modifiers):

![](https://user-images.githubusercontent.com/287848/33090666-01adbc14-cef5-11e7-99eb-00bcacfca0a7.png)

with [`Stream.Length`](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.length):

![](https://user-images.githubusercontent.com/287848/33090697-2e2e7be8-cef5-11e7-8d7f-491b7707faad.png)

I think breadcrumbs are very useful for navigating to related pages, so Roslyn API reference should have them too.

**Comment by BillWagner** [comment]
@dend Is this something you configure at your end?

**Comment by BillWagner** [comment]
Fixed in #31
