### ISSUE TITLE
Quick Start: Build your first analyzer.

### ISSUE THREAD

**Issue by BillWagner** [dotnet/roslyn-api-docs#5]
This should be as simple as possible. `if` without brackets might be good. 

Add unit tests for test cases for code.

**Comment by MaStr11** [comment]
These articles might be a good source for this 

Roslyn Wiki [How To Write a C# Analyzer and Code Fix]https://github.com/dotnet/roslyn/wiki/How-To-Write-a-C%23-Analyzer-and-Code-Fix)

MSDN (C# and Visual Basic - Use Roslyn to Write a Live Code Analyzer for Your API)[https://msdn.microsoft.com/en-us/magazine/dn879356.aspx?f=255&MSPPError=-2147217396]

**Comment by BillWagner** [comment]
Issue moved to [dotnet/docs #4831](https://github.com/dotnet/docs/issues/4831) via [**ZenHub**](https://www.zenhub.com/)
